oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
