<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use \Doctrine\ORM\QueryBuilder;

class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAdvertWithCategories(array $categoryNames)
	{
		$qb = $this
		    ->createQueryBuilder('a')
		    ->leftJoin('a.categories', 'cat')
		    ->addSelect('cat')
		;

		foreach ($categoryNames as $category) {
			$qb
				->andWhere('cat.name = :category')
	       		->setParameter('category', $category)
	       	;
		}

		return $qb
			->getQuery()
			->getResult()
		;	
	}
}
