<?php

namespace OC\PlatformBundle\Repository;

/**
 * HoplieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoplieRepository extends \Doctrine\ORM\EntityRepository
{
}
